### ISSUE TITLE
500 Internal Server Error while viewing/editing documents

### ISSUE THREAD

**Issue by dmakshay2015** [jmakeig/narthex#10]
I was evaluating narthex for MarkLogic 8. I followed the installation instructions on the index page which worked fine. Now the problem is that when I click on a document name or when I try to edit the document, I am getting an exception on the screen. Here is the exception. 

> 500 Internal Server Error
> 
> XDMP-AS: (err:XPTY0004) $variants as element(http:variant)* -- Invalid coercion: <http:variant xmlns:http="xdmp:http"><http:media-type><http:type>application</http:type><http:sub-typ...</http:variant> as element(http:variant)
> in /document.xqy, at 36:86, in xdmp:invoke("document.xqy", (), <options xmlns="xdmp:eval"><database>10877196048510827001</database></options>) [1.0-ml]
> in invoker.xqy, at 16:1 [1.0-ml]
> $_ = ()
> $db = xs:unsignedLong("10877196048510827001")

Please let me know if there are any other steps or configurations which I have to follow in order to resolve this issue.

**Comment by jmakeig** [comment]
This should be resolved by 3de6d977120585e69fe1067af57c6918289c64f9. Thanks @innovimax (and sorry to leave that hanging for so long).
